# Generated by Django 4.2.4 on 2023-08-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(null=True, upload_to='cars/images/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
